book/urls.py
from django.urls import path

from book import views

urlpatterns = [
	path('get_data/', views.get_books_emag, name='get-data')
]

djangoProject/urls.py
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include

from userextend.forms import PasswordChangeNewForm, PasswordResetNewForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('intro.urls')),
    path('', include('home.urls')),
    path('', include('student.urls')),
    path('', include('trainer.urls')),
    path('', include('userextend.urls')),
    path('', include('book.urls')),

    path(
        "password_change/", views.PasswordChangeView.as_view(form_class=PasswordChangeNewForm), name="password_change"
    ),

    path(
        "password_reset/", views.PasswordResetView.as_view(form_class=PasswordResetNewForm), name="password_reset"
    ),
    path('', include('django.contrib.auth.urls')),


]

student/models.py
from django.db import models

from trainer.models import Trainer


class Student(models.Model):

    gender_options = (('male', 'Male'), ('female', 'Female'))

    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    age = models.IntegerField()
    email = models.EmailField(max_length=100)
    description = models.TextField(max_length=300)
    start_date = models.DateTimeField()
    end_date = models.DateField()
    active = models.BooleanField(default=True)
    gender = models.CharField(max_length=6, choices=gender_options)

    trainer = models.ForeignKey(Trainer, on_delete=models.CASCADE, null=True)

    created_at = models.DateTimeField(auto_now_add=True, null=True) #auto_now_add=True il folosim pentru a stoca data si ora cand a fost creata inregistrarea
    updated_at = models.DateTimeField(auto_now=True, null=True) # auto_now il folosim pt a stoca data si ora de fiecare data can actualizam informatii despre studentul nostru


    def __str__(self):
        return f'{self.first_name} {self.last_name}'

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/my_style.css' %}">
</head>
<body class="image_bg">

{% include 'navbar.html' %}
{#<img class="edit_img" src="{% static 'images/mountain.jpg' %}" alt="Copacabana">#}
{% block content %} {% endblock %}
<script src="{% static 'js/my_script.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js" integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js" integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ" crossorigin="anonymous"></script>
</body>
</html>

templates/mail.html
<!DOCTYPE html>
<html>
<head>
  <title>Înregistrare cont</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      line-height: 1.6;
      background-color: #f2f2f2;
      margin: 0;
      padding: 0;
    }

    .container {
      max-width: 600px;
      margin: 0 auto;
      padding: 20px;
      background-color: #ffffff;
    }

    h1 {
      color: #333333;
      margin-top: 0;
    }

    p {
      margin-bottom: 20px;
    }

    .button {
      display: inline-block;
      background-color: #0d316a;
      color: #ffffff;
      padding: 10px 20px;
      text-decoration: none;
      border-radius: 4px;
    }
  </style>
</head>
<body>
  <div class="container">
    <h1>Bună ziua, {{ full_name }}!</h1>
    <p>Vă mulțumim pentru înregistrarea contului dvs.</p>
    <p>Numele de utilizator este: {{ username }} e</p>
    <p>Pentru a vă activa contul și a începe să utilizați serviciile noastre, vă rugăm să faceți clic pe butonul de mai jos:</p>
    <p>
      <a href="https://www.exemplu.com/activare" class="button">Activare cont</a>
    </p>
    <p>Dacă nu ați creat acest cont sau considerați că ați primit acest e-mail din greșeală, vă rugăm să ne contactați cât mai curând posibil.</p>
    <p>Vă mulțumim!</p>
  </div>
</body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Django Project</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home_page' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'get-data' %}">Add books</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                           aria-expanded="false">
                            Intro
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'list-of-cars' %}">List of cars</a></li>
                            <li><a class="dropdown-item" href="{% url 'list-of-carti' %}">List of carti</a></li>
                        </ul>
                    </li>

                    {% if perms.student.add_student or perms.student.view_list_of_students %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                               aria-expanded="false">
                                Student
                            </a>
                            <ul class="dropdown-menu">
                                {% if perms.student.add_student %}
                                    <li><a class="dropdown-item" href="{% url 'create-student' %}">Create a new student</a></li>
                                {% endif %}
                                {% if perms.student.view_list_of_students %}
                                    <li><a class="dropdown-item" href="{% url 'list-of-students' %}">List of students</a></li>
                                {% endif %}
                            </ul>
                        </li>
                    {% endif %}

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                           aria-expanded="false">
                            Trainer
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'create-trainer' %}">Create a new trainer</a></li>
                            <li><a class="dropdown-item" href="{% url 'list-of-trainers' %}">List of trainer</a></li>
                        </ul>
                    </li>
                {% endif %}

            </ul>
            <div>
                {% if user.is_authenticated %}
                    <div class="dropdown" style="padding-right: 10px">
                        <button class="btn btn-outline-info dropdown-toggle" type="button" data-bs-toggle="dropdown"
                                aria-expanded="false">
                            My profile
                        </button>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'password_change' %}">Change password</a></li>
                            <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
                        </ul>
                    </div>
                {% else %}
                    <a href="{% url 'login' %}" class="btn btn-outline-success">Login</a>
                    <a href="{% url 'create-user' %}" class="btn btn-outline-secondary">Sign up</a>
                {% endif %}
            </div>
            <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>